# environment.yml
name: identifiability
channels:
  - conda-forge
  - defaults

dependencies:
  # runtime
  - python=3.11
  - numpy=2.3.0
  - scipy=1.15.3
  - hydra-core=1.3.2
  - structlog=25.4.0

  # pip is required for the remaining packages
  - pip

  # pip-only packages (JAX + dev tools)
  - pip:
    - jax==0.6.1
    - jaxlib==0.6.1

    # dev dependencies
    - pytest==8.4.0
    - pytest-cov==6.2.1
    - black==25.1.0
    - isort==6.0.1
    - flake8==7.2.0
    - mypy==1.16.1
    - Sphinx==8.3.0
    - mkdocs==1.6.1
    - mkdocstrings==0.29.1
